# Generated by Django 3.1.1 on 2020-10-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AddField(
            model_name='employee',
            name='econtact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
